[package]
name = "pomodoro_timer_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
tokio = { version = "1.41.0", features = ["full"] }

